[package]
name = "rust-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
provide-rust = { path = "../.." }
tokio = { version = "1.12.0", features = ["full"] }
serde_json = "1.0.68"
